[package]
name = "vanilla_text"
version = "0.1.0"
authors = ["Koji Matsumoto <otomustam.ijok@gmail.com>"]

[dependencies]
gio = "0.2.0"
gdk = "0.6.0"
gdk-pixbuf = "0.2.0"

[dependencies.gtk]
version = "0.2.0"
features = ["v3_16"]

